### ISSUE TITLE
Blocked for Lack of Credits Despite Having Bought Them

### ISSUE THREAD

**Issue by saeedan2000** [ssraza21/textifyi-issues#2]
Assalamu Alaikum. I've bought 300 credits but I'm periodically faced with an error message when trying to translate jpg images. It usually goes away if I keep trying but I'm attempting to transcribe a ~270 page book so needless to say it's slowing things down. At the moment I'm not able to get past it.

Here's a pic:
![image](https://github.com/user-attachments/assets/46f311be-45d8-4132-8827-87b60fefd6b7)

**Comment by ssraza21** [comment]
Walaikum assalaam, im looking into it. Sorry about this!

**Comment by ssraza21** [comment]
Are you trying to translate?

**Comment by saeedan2000** [comment]
Jazakallah khair for the quick response.

**Comment by saeedan2000** [comment]
No actually, I'm just trying to get arabic text from a picture of an arabic book.

**Comment by ssraza21** [comment]
You should be able to do that from the main home page: https://texti.fyi - feel free to share the image with me

**Comment by saeedan2000** [comment]
Eg: ![PXL_20241108_172934004 1](https://github.com/user-attachments/assets/96eff7cf-461c-4b59-b728-3f34daa49b58)

**Comment by ssraza21** [comment]
It worked for me. I got the output, here it is:
٦٣
الْأَرْضَ ، فَدَلَكَهَا دَلَكًا شَدِيداً ، ثُمَّ تَوَضًا وُضُونَهُ لِلصَّلوةِ ثُمَّ أَفْرَغَ عَلَى
رَأْسِهِ ثَلَك حَفَنَاتٍ 
مِلاً 
كَفْهِ ثُمَّ غَسَلَ سَائِرَ جَسَدِهِ ثُمَّ تَنَحَّى عَنْ مَقَامِهِ
ذلِكَ فَغَسَلَ رِجْلَيْهِ ثُمَّ أَتَيْتُهُ بِالْمَنْدِيلِ فَرَدَّهُ .
رواه البخاري ومسلم وهذا اللفظ لمسلم)
۱۷۳ عَنْ يَعْلَى قَالَ إِنَّ رَسُولَ الله رَأَى رَجُلاً يَغْتَسِلُ بالبراز
فَصَعِدَ الْمِنْبَرَ فَحَمِدَ الله وَ أَثْنى عَلَيْهِ ثُمَّ قَالَ: إِنَّ الله حَى سَتيْرٌ يُحِبُّ
الحَيَاءَ وَالسَّسَتْرَ فَإِذَا اغْتَسَل أَحَدُكُمْ فَلْيَسْتِتر [رواه ابوداود والنسائي)
باب غسل يوم الجمعة ويوم العيد
[رواه البخاري ومسلم]
١٧٤) عَنِ ابْنِ عُمَرَ قَالَ : قَالَ رَسُولُ الله ﷺ : إِذَاجَاءَ أَحدُكُمُ
الجُمْعَةَ فَلْيَغْتَسِلُ.
١٧٥ عَنْ سَمُرَةَ بْنِ جُنْدَبِ قَالَ: قَالَ رَسُولُ اللَّهِ : مَنْ تَوَضًا
يَوْمَ الجُمْعَةَ فَبِهَا وَنِعْمَتْ وَ مَنِ اغْتسَل فَالغُسْلُ أفْضَلُ.
وه و
[رواه احمد وابوداؤد والترمذي والنسائي والدارمي]
١٧٦ ﴾ عَنْ أَبِي هُرَيْرَة قَالَ: قَالَ رَسُوْلُ اللهِ : حَقٌّ عَلَى كُلِّ هر
مُسْلِمٍ أَنْ يَغْتَسِلَ فِي كُلِّ سَبْعَةِ أَيَّامٍ يَوْمًا يَغْسِلُ فِيْهِ رَأْسَهُ وَجَسَدَهُ.
[رواه البخاري ومسلم]
۱۷۷ م عن عبد الله بنِ عَبّاسِ قَالَ : كَانَ رَسُولُ الله يَغْتَسِلُ
[رواه ابن ماجه
يَومَ الفِطْرِ وَيَومَ الأضحى.
[۱۷۳] مشكاة ص ٤٩. قوله بالبراز أى بالفضاء الواسع عرياناً .
[١٧٤ ) مشكاة ص ٥٥ . قوله فليغتسل الأمر 
للاستحباب كما 
يدل عليه الحديث الآتي.
[١٧٥) مشكاة ص ٥٥ . قوله فيها ونعمت. تقديره 
فأهل بتلك الفعلة ونعمت الفعلة 
هي
وروى عن الأصمعي" فبالسنة أخذ " ونعمت 
الخصلة حاشيه مشكاة.
[١٧٦) مشكاة ص ٥٥. قوله حق أى ثابت ولازم أو حرى ولائق.

**Comment by saeedan2000** [comment]
I attempted from the home page but I get stuck here:
![image](https://github.com/user-attachments/assets/ee8a2aa0-8c65-4987-ba7e-67ea439fe707)
Clicking extract brings me back to the same place.

**Comment by ssraza21** [comment]
You should be able to do the pdf but if you cant then lmk!

**Comment by saeedan2000** [comment]
Sorry, I didn't get what you are saying. I'm not seeing the actual text when I upload the image to the home page. It just shows me the above dialog and I'm not sure where to go from there.

**Comment by ssraza21** [comment]
Sorry about that, it does seem like a bug on my end

you can send me the pdf if you want me to give you the text: syedsraza21@gmail.com

**Comment by saeedan2000** [comment]
I don't have a pdf, I've been taking pictures of individual pages of a physical book.

Also, would my results be different because I've been using the translate feature instead of the extract text one? I'm wondering if I've been missing out on accuracy.

**Comment by ssraza21** [comment]
Yeah I'd recommend using the transcribe feature from the homepage. 

Translate feature essentially 
Extracts the text then translates. But that's not useful if you just need to extract the text 

If you're able to find a pdf it would probably make the process much quicker

**Comment by saeedan2000** [comment]
I haven't found a pdf for this book with the commentary this one has. I'll try looking again.

I've already done ~122 pages though so hopefully the unnecessary translation didn't cause too much deviation. I haven't looked too deep into the results but they look pretty good except for a few issues.

**Comment by saeedan2000** [comment]
Ok seems like Extract works if I convert my jpegs to pdfs.

**Comment by saeedan2000** [comment]
Nvm my jpg just worked too.

**Comment by ssraza21** [comment]
Nice that's awesome to hear Alhamdulillah. I didn't want you to convert to pdf just for this 

If you want, you can send me the images and I can transcribe them all in one; I feel bad that you have to do it one by one 😅

inshaAllah adding multiple images will be a feature coming soon

**Comment by saeedan2000** [comment]
I think the issue might have been with dragging and dropping from my phone's internal drive. Seems like when I copy over to my computer's drive first and then upload it works? Not 100% sure yet.

I actually need to finish taking pics as I haven't taken any of the last 150 pages. I might get back to you on that though. The only thing is I need the text of each page to be separated in some way.

**Comment by ssraza21** [comment]
That can be done, let me know when you take the pictures!

**Comment by saeedan2000** [comment]
Here are pics of the remaining pages:
https://drive.google.com/drive/folders/1-166TA6ABcsq9uS8ag7oubVWRZqofkGQ

If you can extract the text with page delineation that would be great. If not I can keep putting them in as well. Jazakallah khairan

**Comment by saeedan2000** [comment]
If u could put it in a Google doc or docx that would work, or whatever's easiest.

**Comment by ssraza21** [comment]
Done! Here is the google doc link with all of the pages: https://docs.google.com/document/d/1f29DgB7WC077DIHN7-cj9Mvcp3xHcoRcPlaZkFs9lgY/edit?usp=sharing

Let me know if it looks good

**Comment by saeedan2000** [comment]
That's exactly what I needed, jazakallah khair. This book is Alfiyyatul Hadith by Molana Manzur Numani and it's hard to find without a lot of printing errors. InshaAllah we are planning to try and create a better edition for personal use and maybe eventually to publish if we get the necessary permissions. Extracting the text is the starting point.

**Comment by saeedan2000** [comment]
Not sure if you want to close this or not as far as the original bug is concerned but my issue is resolved.
